### ISSUE TITLE
Plugin settings is not getting updated

### ISSUE THREAD

**Issue by hchouhan** [flowdee/amazon-product-in-a-post-plugin#19] opened 2020-09-18 15:32 UTC
Changes cannot be saved in the plugin settings.

**Comment by hchouhan** [comment] 2020-09-18 15:32
https://secure.helpscout.net/conversation/1281859877/28640/

**Comment by webdj-agency** [comment] 2020-09-18 17:04
Hey Harish
i visited the client's site admin area, tested the bug and saved the client's "swapped over" AAWP credentials as it should be.
but! it was just a one-time hack and not the solution of his site problem.

deactivating all the plugins (except "query monitor") and switching between the themes didn't help: the notice is still shown.

not sure if the directive "track_errors is deprecated in php 7.3" is related to any plugin.
at least i can't find such code instructions in our AAWP plugin.

looks like the hosting provider have set the "track_errors" value to "On" in the php.ini settings after updating the PHP version to 7.2+:
https://www.php.net/manual/en/language.operators.errorcontrol.php#125245
https://github.com/composer/composer/issues/7365#issuecomment-531086504

or it is set in the .htaccess
or the dev-ops just forgot to restart the server after some updates ))

so while the hosting php setting is misconfigured, such trouble can happen again with any plugin while saving any setting

**Comment by webdj-agency** [comment] 2020-09-18 17:06
![Screenshot](https://user-images.githubusercontent.com/64838430/93625294-60357100-f9ea-11ea-9bdc-a00422c86f13.png)

**Comment by flowdee** [comment] 2020-09-19 06:51
Just for the records: It's not about AAWP ;)

**Comment by webdj-agency** [comment] 2020-09-19 08:39
yeah, my typo. i meant "Amazon Product In a Post". it is present on the screenshot

**Comment by hchouhan** [comment] 2020-09-19 08:50
@webdj-agency I would recommend asking the client for permission before switching themes. I had got into an issue doing this once.

BTW, same issue is also on our test site at https://dev.flowdee.de/amazon-product-in-a-post-plugin/wp-admin/admin.php?page=apipp_plugin_admin.

Try removing the value of "Tracking ID" and click "Save Changes" and then see what happens.

**Comment by hchouhan** [comment] 2020-09-19 09:20
https://secure.helpscout.net/conversation/1284435347/28704

**Comment by webdj-agency** [comment] 2020-09-19 10:50
tested on my local and reproduced the bug ((

i rolled back the local git history to find out when it started.

switching to the commit https://github.com/flowdee/amazon-product-in-a-post-plugin/commit/b7f1ca1591f62e7b20e8456b10d464a6a46ccc23 i can delete the "Amazon Affiliate ID" and the empty value is saved

but switching to the next commit: https://github.com/flowdee/amazon-product-in-a-post-plugin/commit/a02f4971c12bcbcbf1288a6d996a2d1ffcaa6457 the "Amazon Affiliate ID" becomes unchangeable

![Screenshot](https://user-images.githubusercontent.com/64838430/93665216-6f193380-fa7d-11ea-99c7-b7cb0c0da781.png)

@flowdee looks like the bug appears on this refactoring commit: https://github.com/flowdee/amazon-product-in-a-post-plugin/commit/a02f4971c12bcbcbf1288a6d996a2d1ffcaa6457

**Comment by webdj-agency** [comment] 2020-09-19 11:02
also detected that the Delete cache buttons are not working: https://dev.flowdee.de/amazon-product-in-a-post-plugin/wp-admin/admin.php?page=apipp-cache-page

but not sure if it is related to this refactoring or was earlier

**Comment by webdj-agency** [comment] 2020-09-19 12:57
Found and fixed.

@hchouhan we can forget about the "track_errors is deprecated in php 7.3" notice. it is not related to our plugin

**Comment by flowdee** [comment] 2020-09-19 16:23
Thanks @webdj-agency .

Going to release the update on Monday @hchouhan

**Comment by flowdee** [comment] 2020-09-20 07:42
Fixed with the release of v5.2.1 now.  

https://wordpress.org/plugins/amazon-product-in-a-post-plugin/#developers

FYI @hchouhan

**Closed by flowdee** 2020-09-20 07:42 UTC
Labels: bug
